<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array>
    <string>dat</string>
   </array>
  <key>name</key>
  <string>osiac_microcode</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.osiac_microcode</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(^[^\s]+.*)</string>
          <key>name</key>
          <string>comment.osiac_microcode</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\bst=)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>constant.language.osiac_microcode</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#main__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\s|$)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>constant.language.osiac_microcode</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>((\brac=)|(\brn=)|(\bwac=)|(\bwn=))</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>variable.parameter.osiac_microcode</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#main__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\s|$)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>variable.parameter.osiac_microcode</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>((\bit1\b)|(\bot1\b)|(\bit2\b)|(\bot2\b)|(\bit3\b)|(\bot3\b)|(\bit4\b)|(\bot4\b)|(\bit5\b)|(\bot5\b)|(\biq\b)|(\boq\b)|(\biir\b)|(\bimar\b)|(\bimdr\b)|(\bomdr\b))</string>
          <key>name</key>
          <string>variable.parameter.osiac_microcode</string>
        </dict>
        <dict>
          <key>match</key>
          <string>((\boa\b)|(\bib\b)|(\bcomp\b)|(\bp1\b)|(\boadder\b))</string>
          <key>name</key>
          <string>variable.parameter.osiac_microcode</string>
        </dict>
        <dict>
          <key>match</key>
          <string>((\bread\b)|(\bwrite\b))</string>
          <key>name</key>
          <string>variable.parameter.osiac_microcode</string>
        </dict>
        <dict>
          <key>match</key>
          <string>((\bnewc\b)|(\bnewv\b)|(\bnewz\b)|(\bnewn\b)|(\bsetc\b)|(\bclrc\b)|(\bsetv\b)|(\bclrv\b))</string>
          <key>name</key>
          <string>variable.parameter.osiac_microcode</string>
        </dict>
        <dict>
          <key>match</key>
          <string>((\bhalt\b))</string>
          <key>name</key>
          <string>variable.parameter.osiac_microcode</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>((\bnst=)|(\bvalue=))</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.control.osiac_microcode</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#main__3</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\s|$)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.control.osiac_microcode</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\bcond=\&apos;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.control.osiac_microcode</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#main__4</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\&apos;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.control.osiac_microcode</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\brt=\&apos;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>support.function.osiac_microcode</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>string.quoted.osiac_microcode</string>
          <key>end</key>
          <string>(\&apos;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>support.function.osiac_microcode</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\s])</string>
          <key>name</key>
          <string>invalid.osiac_microcode</string>
        </dict>
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\s])</string>
          <key>name</key>
          <string>invalid.osiac_microcode</string>
        </dict>
       </array>
    </dict>
    <key>main__2</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\s])</string>
          <key>name</key>
          <string>invalid.osiac_microcode</string>
        </dict>
       </array>
    </dict>
    <key>main__3</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\s])</string>
          <key>name</key>
          <string>invalid.osiac_microcode</string>
        </dict>
       </array>
    </dict>
    <key>main__4</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>((\bir1512\b)|(\bir109\b)|(\bir8\b)|(\bir108\b)|(\bir65\b)|(\bir11\b)|(\bir4\b)|(\bir64\b)|(\bir118\b)|(\bir158\b)|(\bir3\b)|(\bir7\b)|(\bir2\b)|(\bir1\b)|(\bir0\b)|(\bir76\b)|(\bir75\b)|(\bibrch\b)|(\bir5\b))</string>
          <key>name</key>
          <string>entity.name.type.osiac_microcode</string>
        </dict>
        <dict>
          <key>match</key>
          <string>((\bcout\b)|(\bvout\b)|(\bbusz\b)|(\bbusn\b)|(\bv\b)|(\bz\b)|(\bn\b)|(\bc\b))</string>
          <key>name</key>
          <string>entity.name.type.osiac_microcode</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\s]|\s)</string>
          <key>name</key>
          <string>invalid.osiac_microcode</string>
        </dict>
       </array>
    </dict>
    <key>main__5</key>
    <dict>
      <key>patterns</key>
      <array>
       </array>
    </dict>
    <key>numeric</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(\b\d+)</string>
          <key>name</key>
          <string>constant.numeric.osiac_microcode</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
